Library/Models/Book.cs
using System.Collections.Generic;
using Library.Models;

namespace Library.Models
{
  public class Book
  {
    public Book()
    {
      this.Authors = new HashSet<AuthorBook>();
    }

    public int BookId { get; set; }
    public string Title { get; set; }
    public virtual ApplicationUser User { get; set; }

    public ICollection<AuthorBook> Authors { get; set; }

    public ICollection<BookCheckout> Checkouts { get; set; }

  }
}

Library/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Library.Controllers
{
  [Authorize]
  public class BooksController : Controller
  {
    private readonly LibraryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public BooksController(UserManager<ApplicationUser> userManager, LibraryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userBooks = _db.Books.Where(entry => entry.User.Id == currentUser.Id);
      return View(userBooks);
    }

    public ActionResult Create()
    {
      ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "AuthorName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Book book, int AuthorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      book.User = currentUser;
      _db.Books.Add(book);
      if (AuthorId != 0)
      {
        _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisBook = _db.Books
          .Include(book => book.Authors)
          .ThenInclude(join => join.Author)
          .FirstOrDefault(book => book.BookId == id);
      return View(thisBook);
    }

    public ActionResult Edit(int id)
    {
      var thisBook = _db.Books.FirstOrDefault(books => books.BookId == id);
      ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "AuthorName");
      return View(thisBook);
    }

    [HttpPost]
    public ActionResult Edit(Book book, int AuthorId)
    {
      if (AuthorId != 0)
      {
        _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId });
      }
      _db.Entry(book).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddAuthor(int id)
    {
      var thisBook = _db.Books.FirstOrDefault(books => books.BookId == id);
      ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "AuthorName");
      return View(thisBook);
    }

    [HttpPost]
    public ActionResult AddAuthor(Book book, int AuthorId)
    {
      if (AuthorId != 0)
      {
        _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisBook = _db.Books.FirstOrDefault(books => books.BookId == id);
      return View(thisBook);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisBook = _db.Books.FirstOrDefault(books => books.BookId == id);
      _db.Books.Remove(thisBook);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteAuthor(int joinId)
    {
      var joinEntry = _db.AuthorBook.FirstOrDefault(entry => entry.AuthorBookId == joinId);
      _db.AuthorBook.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Search(string search)
    {
      List<Book> model = _db.Books.Where(book => (book.Title.Contains(search))).ToList();

      return View(model);
    }
  }
}

Library/Controllers/CheckoutsController.cs
using Microsoft.AspNetCore.Mvc;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

//new using directives
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Library.Controllers
{
  [Authorize] //new line
  public class CheckoutsController : Controller
  {
    private readonly LibraryContext _db;
    private readonly UserManager<ApplicationUser> _userManager; //new line

    //updated constructor
    public CheckoutsController(UserManager<ApplicationUser> userManager, LibraryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    //updated Index method
    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userCheckouts = _db.Checkouts.Where(entry => entry.User.Id == currentUser.Id);
      return View(userCheckouts);
    }
    [HttpGet]
    public ActionResult Checkout(int bookId)
    {
      BookCheckout thisCheckout = _db.BookCheckout.FirstOrDefault(checkouts => checkouts.CheckoutId == bookId);
      ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
      return View(thisCheckout);
    }
  
  }
}

    // public ActionResult Create()
    // {
    //   ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
    //   return View();
    // }

    // //updated Create post method
    // [HttpPost]
    // public async Task<ActionResult> Create(Checkout checkout, int BookId)
    // {
    //   var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    //   var currentUser = await _userManager.FindByIdAsync(userId);
    //   checkout.User = currentUser;
    //   _db.Checkouts.Add(checkout);
    //   if (BookId != 0)
    //   {
    //     _db.BookCheckout.Add(new BookCheckout(checkout.CheckoutId, BookId) { BookId = BookId, CheckoutId = checkout.CheckoutId });
    //   }
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
    // }

    // public ActionResult Details(int id)
    // {
    //   var thisCheckout = _db.Checkouts
    //       .Include(checkout => checkout.Books)
    //       .ThenInclude(join => join.Book)
    //       .FirstOrDefault(checkout => checkout.CheckoutId == id);
    //   return View(thisCheckout);
    // }

    // public ActionResult Edit(int id)
    // {
    //   var thisCheckout = _db.Checkouts.FirstOrDefault(checkouts => checkouts.CheckoutId == id);
    //   ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
    //   return View(thisCheckout);
    // }

    // [HttpPost]
    // public ActionResult Edit(Checkout checkout, int BookId)
    // {
    //   if (BookId != 0)
    //   {
    //     _db.BookCheckout.Add(new BookCheckout(checkout.CheckoutId, BookId) { BookId = BookId, CheckoutId = checkout.CheckoutId });
    //   }
    //   _db.Entry(checkout).State = EntityState.Modified;
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
    // }

    // public ActionResult AddBook(int id)
    // {
    //   var thisCheckout = _db.Checkouts.FirstOrDefault(checkouts => checkouts.CheckoutId == id);
    //   ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
    //   return View(thisCheckout);
    // }

    // [HttpPost]
    // public ActionResult AddBook(Checkout checkout, int BookId)
    // {
    //   if (BookId != 0)
    //   {
    //     _db.BookCheckout.Add(new BookCheckout(checkout.CheckoutId, BookId) { BookId = BookId, CheckoutId = checkout.CheckoutId });
    //   }
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
    // }

    // public ActionResult Delete(int id)
    // {
    //   var thisCheckout = _db.Checkouts.FirstOrDefault(checkouts => checkouts.CheckoutId == id);
    //   return View(thisCheckout);
    // }

    // [HttpPost, ActionName("Delete")]
    // public ActionResult DeleteConfirmed(int id)
    // {
    //   var thisCheckout = _db.Checkouts.FirstOrDefault(checkouts => checkouts.CheckoutId == id);
    //   _db.Checkouts.Remove(thisCheckout);
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
    // }

    // [HttpPost]
    // public ActionResult DeleteAuthor(int joinId)
    // {
    //   var joinEntry = _db.BookCheckout.FirstOrDefault(entry => entry.BookCheckoutId == joinId);
    //   _db.BookCheckout.Remove(joinEntry);
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
    // }
    
    // [HttpPost]
    
    // public ActionResult Checkout(Checkout checkout, List<int> BookId)
    // {
    //   foreach (var id in BookId)
    //   {
    //     Book book = _db.Books.FirstOrDefault(checkouts => checkouts.BookId == id);
    //     BookCheckout thisCheckout = new BookCheckout(checkout.CheckoutId, book.BookId);
    //     _db.BookCheckout.Add(thisCheckout);
    //   }
    //   _db.SaveChanges();
    //   return RedirectToAction("Index");
//     }
//   }
// }

Library/Views/Books/AddAuthor.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<h2>Add an author</h2>

<h4>Add an author to this book: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.BookId)

    @Html.Label("Select author")
    @Html.DropDownList("AuthorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Library/Views/Books/Create.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<h4>Add a new book</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Title)
    @Html.TextBoxFor(model => model.Title)

    @Html.Label("Select author")
    @Html.DropDownList("AuthorId")

    <input type="submit" value="Add new book" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all books", "Index")</p>

Library/Views/Books/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<h2>Are you sure you want to delete this book?</h2>

@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Library/Views/Books/Details.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<h2>Book Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)</h3>

@if(@Model.Authors.Count == 0)
{
  <p>This book does not belong to any authors</p>
}
else
{
  <h4>Authors the book belongs to:</h4>
  <ul>
  @foreach(var join in Model.Authors)
  {
    <li>@join.Author.AuthorName</li>
    @using (Html.BeginForm("Deleteauthors", "Books"))
    {
      @Html.Hidden("joinId", @join.BookId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}
<p>@Html.ActionLink("Check this book out", "Checkout", "Checkouts", new { id = Model.BookId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Book", "Edit", new { id = Model.BookId })</p>
<p>@Html.ActionLink("Add a Author", "AddAuthor", new { id = Model.BookId })</p>
<p>@Html.ActionLink("Delete Book", "Delete", new { id = Model.BookId })</p>

Library/Views/Books/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<h2>Edit</h2>

<h4>Edit this book: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.BookId)

    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)

    @Html.Label("Select author")
    @Html.DropDownList("AuthorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Library/Views/Books/Index.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models;
@using System.Security.Claims
@model IEnumerable<Library.Models.Book>

<h1>Books for @User.Identity.Name</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Book book in Model)
    {
      <li>@Html.ActionLink($"{book.Title}", "Details", new { id = book.BookId })</li>
    }
  </ul>
} 
else
{
  <h3>No books have been added yet!</h3>
}

<p>@Html.ActionLink("Add new book", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

Library/Views/Books/Search.cshtml
@{
  Layout = "_Layout";
}
@using Library.Models;
@model List<Library.Models.Book>;

<h1>SEARCH</h1>

@if(Model.Count == 0)
{
  <p> No book titles match this search </p>
}
else
{
  <ul>
    @foreach(Book book in Model)
    {
      <li> @Html.ActionLink($"{book.Title}", "Details", new {id = book.BookId}) : @book.Title</li>
    }
  </ul>
}
<p>@Html.ActionLink("Back to books", "Index")</p>
<p>@Html.ActionLink("Add new book", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>